export const EMAIL_CHANGED = 'email_changed'
export const PHONE_NUMBER_CHANGED = 'phone_number_changed'
export const BUSINESS_NAME_CHANGED = 'business_name_changed'
export const PASSWORD_CHANGED = "password_changed"
export const C_PASSWORD_CHANGED = "c_password_changed"
export const ADDRESS_CHANGED = "address_changed"
export const     LOGIN_SUCCESS ="login_success"
export const     LOGIN_FAIL ="login_fail"
export const     AUTH_LOADER ="auth_loader"
export const     LOG_OUT ="log_out"
export const     SET_INTERNET_STATE ="set_internet_state"
export const     AUTHLOADER_OFF ="authloader_off"
export const     SET_COUNTRY_CODE ="set_country_code"
export const     SET_APP_STATE ="set_app_state"
export const     SET_PICKUP_ADDRESS = 'set_pickup_address'
export const ORDER_LOADER = 'order_loader'
export const SET_DROPOFF_ADDRESS = 'set_dropoff_address'
export const ORDER_LOADER_OFF = 'order_loader_off'
export const PACKAGE_QUANTITY_CHANGED = 'package_quantity_changed'
export const PACKAGE_DESCRIPTION_CHANGED = 'package_description_changed'
export const GET_VEHICLES = 'get_vehicles'
export const SELECT_VEHICLE = 'select_vehicle'
export const SAVE_ORDER = 'save_order'
export const GET_ORDERS = 'get_orders'
export const TOKEN_SENT = 'token_sent'
export const RECIPIENT_PHONE = 'recipient_phone'
export const RECIPIENT_NAME = 'recipient_name'
export const CLOSE_PAYMENT_MODAL = 'close_payment_modal'
export const CANCEL_ORDER = 'cancel_order'
export const TRACKING_ORDER_ID = 'tracking_order_id'
export const  PROFILE_EDITED = 'profile_edited'
export const SET_IMAGE_URL = 'set_image_url'
export const OPEN_PROFILE_BOTTOMSHEET = 'open_profile_bottomsheet'
export const CLOSE_PROFILE_BOTTOMSHEET = 'close_profile_bottomsheet'
export const OLD_PASSWORD = 'old_password'
